### ISSUE TITLE
Support for disabling / toggling the blur effect

### ISSUE THREAD

**Issue by nbartlomiej** [nbartlomiej/foggy#1]
As of now there's no easy way to disable the fog effect.

It should be possible to e.g. call foggy with "false"

```
$('selector').foggy(false)
```

This should bring back the original, unblurred content (and the DOM should look exactly the same as before foggy's actions).

**Comment by jerryyanmj** [comment]
when will this be supported?

**Comment by nbartlomiej** [comment]
I plan to add it in about one week.

**Comment by nbartlomiej** [comment]
Actually, I did it quicker and it's now ready. The feature is present in the 1.1 release, you can get it from here: http://nbartlomiej.github.com/foggy/ .
