### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by jerryyanmj** [nbartlomiej/foggy#2]
Thanks for adding the reset so quickly.

However I do realize there is a 3-4 seconds delay if the DOM gets fancy.

**Comment by nbartlomiej** [comment]
Glad that you like it. Regarding performance: please provide more details. Preferably:
- in what browser (type, version) does the issue occur
- example of the DOM that causes a delay (e.g. at jsfiddle / pastie)

**Comment by jerryyanmj** [comment]
Sorry, I think it is fine as long as I do not put 64 or higher as the quality.

**Comment by nbartlomiej** [comment]
OK, thanks for the information! I'm closing this issue then.
If you have any troubles or have some feedback, feel free to open a new issue.

Cheers!
