### ISSUE TITLE
Foggy in NPM

### ISSUE THREAD

**Issue by mtgibbs** [nbartlomiej/foggy#22]
Hey @nbartlomiej,

I noticed that you have a package.json in the project, but foggy is nowhere to be found on npm.  Is it under a different name there?

**Comment by mookman288** [comment]
@mtgibbs, I don't believe that @nbartlomiej is currently supporting this package. It's not up on npm as far as I know. You can add it to npm as a custom repo though:

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by mtgibbs** [comment]
Lol, Yeah I noticed the times as soon as I submitted the issue and popped back out to the repo page.  Going to close and just link using the git url.  Thanks for responding.  You seem to have the latest fork, you maintaining this now?

**Comment by mookman288** [comment]
@mtgibbs I'm making updates, I wouldn't say I'm actively maintaining. I considered it, but I wasn't sure if that would step on @nbartlomiej toes.
